baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Anubis2 Demo Site"
theme = "anubis2"

[pagination]
pagerSize = 5

[params.author]
name = "Junyi"
email  = "me@junyi.dev"
location = "Singapore"
avatar = "https://avatars.githubusercontent.com/u/123456789?v=4"

[params]
description = "Anubis2 is another simple minimalist theme for Hugo blog engine."
dateFormat = "2006-01-02"
paginationSinglePost = true

rssIcon = false
locale = "en-us"

[params.anubis2]
    hideFooterAttribution = false # hide "Powered by Hugo, theme" in footer

    enableMathGlobally = true # MathJax (default is false)
    enableCopyCodeButton = true
    enableSummary = true # the summary is the preview of the post, if you disable it, the post will be shown only with the title.
    enableReadMoreButton = false
    enableRssIcon = true
    enableColorThemeSwitcher = true
    colorTheme = "auto"
    openInNewTab = true # open links in new tab
    
    tocWordCount = 0 # 0: disable toc. N: show toc if the post has more than N words.
    readNextPosts = 10 # 0: disable this feature. 1: show 1 related posts. N: show N related posts.

    police = "京公网安备 12345678号" # for China ICP police beian
    icp = "京ICP备xxxxx号-1" # for China ICP license

    ## Social Icons
    socialIcons = [
        { id = "docs", url = "https://gohugo.io/documentation/" },
        { id = "github", url = "https://github.com/hugo-theme-anubis2/hugo-theme-anubis2" },
        { id = "linkedin", url = "https://www.linkedin.com/" },
        { id = "email", url = "example@example.com" },
        { id = "facebook", url = "#" },
        { id = "instagram", url = "#" },
        { id = "netease-music", url = "#" },
        { id = "telegram", url = "#" },
        { id = "x", url = "#" },
        { id = "youtube", url = "#" },
        { id = "bluesky", url = "#" }
    ]

    customCSS = [
        "custom-css/custom1.scss", 
        "custom-css/custom2.css",
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    ]

    customJS = [
        "https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"
    ]

    [params.anubis2.services]
        [params.anubis2.services.giscus]
            # Giscus Comment System https://giscus.app/
            repo        = "hugo-theme-anubis2/hugo-theme-anubis2"
            repoId      = "R_kgDOLEp76Q"
            category    = "General"
            categoryId  = "DIC_kwDOLEp76c4CcbPS"
            dataMapping = "pathname"
            lazyLoad    = false

        # [params.anubis2.services.disqus]
        #   shortName = "junyide-xiao-wu"

        # [params.anubis2.services.utterances]
        #   repo = "hugo-theme-anubis2/hugo-theme-anubis2"
        #   theme = "github-light"
        #   issueTerm = "pathname"

        [params.anubis2.services.umami]
            # Umami Analytics https://umami.is/
            id = "e4f661ff-9a8c-49d4-b3cc-2efe553e3973"                                            # Website ID
            url = "https://umami.xtra.science/script.js"
            datacache = false
            dnt       = false
            # if shareUrl is set, a button will be shown on the end of each page
            shareUrl = "https://cloud.umami.is/share/CUTKp6yiDQllAqq9/hugo-theme-anubis2.netlify.app"

        [params.anubis2.services.googleAnalytics]
            # Google Analytics https://analytics.google.com/
            gtag    = "G-32F16X8HLF"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 4

[languages]
[languages.en]
languageName = "English"

[languages.pl]
languageName = "Polski"

[[languages.pl.menu.main]]
identifier = "home"
name = "Strona Główna"
url = "/"
weight = 1

[[languages.pl.menu.main]]
identifier = "about"
name = "O Hugo"
url = "/about/"
weight = 2

[[languages.pl.menu.main]]
identifier = "tags"
name = "Tagi"
url = "/tags/"
weight = 3

[[languages.pl.menu.main]]
identifier = "archive"
name = "Archiwum"
url = "/posts/"
weight = 4

[languages.pl.params]
languageCode = "pl-pl"

[languages.zh]
languageName = "Chinese"

[[languages.zh.menu.main]]
identifier = "home"
name = "首页"
url = "/"
weight = 1

[[languages.zh.menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 2

[[languages.zh.menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 3

[[languages.zh.menu.main]]
identifier = "archive"
name = "归档"
url = "/posts/"
weight = 4

[languages.zh.params]
languageCode = "zh-cn"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style              = 'catppuccin-frappe' # Find more style at here: https://swapoff.org/chroma/playground/
tabWidth           = 4
