[build]
publish = "example-site/public"
command = "cd example-site && hugo --themesDir=../.. --baseURL $URL --config hugo.full.toml"

[build.environment]
HUGO_VERSION = "0.145.0"
HUGO_THEME = "repo"

[context.deploy-preview]
command = "cd example-site &&  hugo --themesDir=../.. --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL --config hugo.full.toml"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
